config/routes.rb
Rails.application.routes.draw do
  get 'tasks/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "tasks", to: 'tasks#index'
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"
  get "tasks/:id/edit", to: 'tasks#edit', as: :edit_task
  get "tasks/:id", to: 'tasks#show', as: :task
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    # raise
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new # Needed to instantiate the form_with
  end

  def create
    @task = Task.new(task_params)
    @task.save # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to task_path(@task)
  end

  def edit
    # @task = Task.find(params[:id])
  end

  def update
    # raise
    # @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    # @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def find_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="container" >
  <%= form_with model: @task do |f| %>
  <div class="completed">
    <div class="label">
      <%= f.label :title %>
    </div>
    <%= f.text_field :title %>
  </div>
  <div class="completed">
  <div class="label">
    <%= f.label :details %>
  </div>
    <%= f.text_field :details %>
  </div>
  <!-- Pour ne pas affchier "completed pour les nouvelles données : -->
  <% unless f.object.new_record? %>
    <div class="completed" >
        <%= f.label :completed %>
        <%= f.check_box :completed %>
    </div>
  <% end %>
  <%= f.submit %>

  <% end %>
</div>

app/views/tasks/edit.html.erb
<%= render "form", task: @task %>

<%# code de base : %>
<!--
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>
-->

app/views/tasks/index.html.erb
<h1>My Tasks#index</h1>

<ul> <% @tasks.each do |task| %>
  <li>  <%= link_to task.title, task_path(task) %> </li>

<% end %>
</ul>

<button>
  <%= link_to "add a new task", tasks_new_path %>
</button>

<p>Find me in app/views/tasks/index.html.erb</p>

app/views/tasks/new.html.erb
<%= render "form", task: @task %>

<%# code de base : %>
<!--
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>
-->

app/views/tasks/show.html.erb
<h1>This is Task # <%= @task.id %></h1>
<p> - Title : <%= @task.title %> </p>
<p> - Details : <%= @task.details %> </p>

<button>
  <%= link_to "Edit this task", edit_task_path %>
</button>

<button>
  <%= link_to "Delete",
    task_path(@task),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %>
</button>

<button>
  <%= link_to "Back to MyTasks", tasks_path %>
</button>